PING_SERVERS = [
    "8.8.8.8"
]

HTTP_SERVERS = [
    "172.217.21.14",
    "213.180.204.62",
    "google.com",
    "walla.com"
]

TEST_DOMAINS = [
    "google.com",
    "yandex.com"
]

DNS_SERVERS = [
    "8.8.8.8",
    "4.4.4.4",
    "199.85.126.10"
]

NETBIOS_PORT = 139
SMB_DEFAULT_PORT = 445
RPC_NETLOGON_PORT = 135
UDP_NETBIOS_PORTS = (137, 138)

LDAP_DEFAULT_PORT = 389
LDAPS_DEFAULT_PORT = 636
GLOBAL_CATALOG_LDAP_DEFAULT_PORT = 3268
GLOBAL_CATALOG_LDAPS_DEFAULT_PORT = 3269
KERBEROS_DEFAULT_PORT = 88
KERBEROS_PASSWORD_CHANGE_PORT = 464
DFS_DEFAULT_PORT = 5722
DYNAMIC_PORT_RANGE_2003 = (1025, 5000)
DYNAMIC_PORT_RANGE_2008 = (49152, 65535)

WINDOWS_TIME_UDP_PORT = 123

HTTP_DEFAULT_PORT = 80
HTTPS_DEFAULT_PORT = 443

SMTP_DEFAULT_PORT = 25
SMTP_SUBMISSION_PORT = 587
SMTPS_DEFAULT_PORT = 485
POP3_DEFAULT_PORT = 110
SECURE_POP3_DEFAULT_PORT = 995
IMAP_DEFAULT_PORT = 143
IMAPS_DEFAULT_PORT = 993
IMAP4_SSL_DEFAULT_PORT = 585

MYSQL_DEFAULT_PORT = 3306
POSTGRESQL_DEFAULT_PORT = 5432
MSSQL_DEFAULT_PORT = 1433
MSSQL_BROWSER_DEFAULT_PORT = 1434
MSSQL_ANALYSIS_SERVICES_PORT = 2383
ORACLE_SQL_DEFAULT_PORT = 1521
ORACLE_SQL_MANAGER_PORT = 1630

WINDOWS_WORKSTATION_PORTS = [NETBIOS_PORT, SMB_DEFAULT_PORT, RPC_NETLOGON_PORT]
LDAP_SERVER_PORTS = [LDAP_DEFAULT_PORT, LDAPS_DEFAULT_PORT,
                     GLOBAL_CATALOG_LDAP_DEFAULT_PORT, GLOBAL_CATALOG_LDAPS_DEFAULT_PORT]
MICROSOFT_AD_DS_PORTS = [LDAP_SERVER_PORTS, KERBEROS_DEFAULT_PORT, KERBEROS_PASSWORD_CHANGE_PORT,
                         DFS_DEFAULT_PORT, DYNAMIC_PORT_RANGE_2003, DYNAMIC_PORT_RANGE_2008]
WEB_SERVER_PORTS = [HTTP_DEFAULT_PORT, HTTPS_DEFAULT_PORT]
MAIL_SERVER_PORTS = [SMTP_DEFAULT_PORT, SMTP_SUBMISSION_PORT, SMTPS_DEFAULT_PORT,
                     POP3_DEFAULT_PORT, SECURE_POP3_DEFAULT_PORT,
                     IMAP_DEFAULT_PORT, IMAPS_DEFAULT_PORT, IMAP4_SSL_DEFAULT_PORT]
SQL_SERVER_PORTS = [MYSQL_DEFAULT_PORT, MSSQL_DEFAULT_PORT, MSSQL_BROWSER_DEFAULT_PORT, MSSQL_ANALYSIS_SERVICES_PORT,
                    POSTGRESQL_DEFAULT_PORT, ORACLE_SQL_DEFAULT_PORT, ORACLE_SQL_MANAGER_PORT]