IS_IN_DOMAIN_WMI_CHECK_SCORE = 5
IS_IN_DOMAIN_COMPUTER_NAME_CHECK_SCORE = 5
IS_IN_DOMAIN_ENVIRONMENT_VARIABLE_CHECK_SCORE = 5

IS_CONNECTED_TO_INTERNET_ICMP_SCORE = 5
IS_CONNECTED_TO_INTERNET_HTTP_SCORE = 5
IS_CONNECTED_TO_INTERNET_DNS_SCORE = 5
IS_CONNECTED_TO_INTERNET_HTTPS_SCORE = 5
